// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

type Service struct {
	ID         int64
	Preset     string
	Name       string
	Url        string
	Profile    string
	Position   int64
	Enabled    int64
	BadgeRegex string
	Favicon    []byte
}

type Setting struct {
	Key   string
	Value string
}
