// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package store

import (
	"context"
)

const countServices = `-- name: CountServices :one
SELECT COUNT(*) FROM services
`

func (q *Queries) CountServices(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countServices)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createService = `-- name: CreateService :one
INSERT INTO services (preset, name, url, profile, position)
VALUES (?, ?, ?, ?, ?)
RETURNING id, preset, name, url, profile, position, enabled, badge_regex, favicon
`

type CreateServiceParams struct {
	Preset   string
	Name     string
	Url      string
	Profile  string
	Position int64
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (Service, error) {
	row := q.db.QueryRowContext(ctx, createService,
		arg.Preset,
		arg.Name,
		arg.Url,
		arg.Profile,
		arg.Position,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Preset,
		&i.Name,
		&i.Url,
		&i.Profile,
		&i.Position,
		&i.Enabled,
		&i.BadgeRegex,
		&i.Favicon,
	)
	return i, err
}

const deleteService = `-- name: DeleteService :exec
DELETE FROM services WHERE id = ?
`

func (q *Queries) DeleteService(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteService, id)
	return err
}

const getSetting = `-- name: GetSetting :one
SELECT value FROM settings WHERE key = ?
`

func (q *Queries) GetSetting(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getSetting, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const listAllServices = `-- name: ListAllServices :many
SELECT id, preset, name, url, profile, position, enabled, badge_regex, favicon FROM services ORDER BY position, id
`

func (q *Queries) ListAllServices(ctx context.Context) ([]Service, error) {
	rows, err := q.db.QueryContext(ctx, listAllServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.Preset,
			&i.Name,
			&i.Url,
			&i.Profile,
			&i.Position,
			&i.Enabled,
			&i.BadgeRegex,
			&i.Favicon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledServices = `-- name: ListEnabledServices :many
SELECT id, preset, name, url, profile, position, enabled, badge_regex, favicon FROM services WHERE enabled = 1 ORDER BY position, id
`

func (q *Queries) ListEnabledServices(ctx context.Context) ([]Service, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.Preset,
			&i.Name,
			&i.Url,
			&i.Profile,
			&i.Position,
			&i.Enabled,
			&i.BadgeRegex,
			&i.Favicon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProfiles = `-- name: ListProfiles :many
SELECT profile FROM services
`

func (q *Queries) ListProfiles(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var profile string
		if err := rows.Scan(&profile); err != nil {
			return nil, err
		}
		items = append(items, profile)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putSetting = `-- name: PutSetting :exec
INSERT INTO settings (key, value) VALUES (?, ?)
ON CONFLICT (key) DO UPDATE SET value = excluded.value
`

type PutSettingParams struct {
	Key   string
	Value string
}

func (q *Queries) PutSetting(ctx context.Context, arg PutSettingParams) error {
	_, err := q.db.ExecContext(ctx, putSetting, arg.Key, arg.Value)
	return err
}

const setServiceBadgeRegex = `-- name: SetServiceBadgeRegex :exec
UPDATE services SET badge_regex = ? WHERE id = ?
`

type SetServiceBadgeRegexParams struct {
	BadgeRegex string
	ID         int64
}

func (q *Queries) SetServiceBadgeRegex(ctx context.Context, arg SetServiceBadgeRegexParams) error {
	_, err := q.db.ExecContext(ctx, setServiceBadgeRegex, arg.BadgeRegex, arg.ID)
	return err
}

const setServiceEnabled = `-- name: SetServiceEnabled :exec
UPDATE services SET enabled = ? WHERE id = ?
`

type SetServiceEnabledParams struct {
	Enabled int64
	ID      int64
}

func (q *Queries) SetServiceEnabled(ctx context.Context, arg SetServiceEnabledParams) error {
	_, err := q.db.ExecContext(ctx, setServiceEnabled, arg.Enabled, arg.ID)
	return err
}

const setServiceFavicon = `-- name: SetServiceFavicon :exec
UPDATE services SET favicon = ? WHERE id = ?
`

type SetServiceFaviconParams struct {
	Favicon []byte
	ID      int64
}

func (q *Queries) SetServiceFavicon(ctx context.Context, arg SetServiceFaviconParams) error {
	_, err := q.db.ExecContext(ctx, setServiceFavicon, arg.Favicon, arg.ID)
	return err
}

const updateServicePosition = `-- name: UpdateServicePosition :exec
UPDATE services SET position = ? WHERE id = ?
`

type UpdateServicePositionParams struct {
	Position int64
	ID       int64
}

func (q *Queries) UpdateServicePosition(ctx context.Context, arg UpdateServicePositionParams) error {
	_, err := q.db.ExecContext(ctx, updateServicePosition, arg.Position, arg.ID)
	return err
}
