// Package store is bender's persistence: a single SQLite database holding
// the configured services and app settings. Queries are generated by sqlc;
// this file owns opening, migrating, and seeding.
package store

import (
	"context"
	"database/sql"
	"embed"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"

	_ "modernc.org/sqlite"

	"github.com/pietjan/bender/internal/service"
)

//go:embed migrations/*.sql
var migrations embed.FS

// Store wraps the database with the generated query set.
type Store struct {
	*Queries
	db *sql.DB
}

// DefaultPath returns the database path under the user config directory
// (e.g. %LOCALAPPDATA%\bender\bender.db on Windows).
func DefaultPath() (string, error) {
	dir, err := os.UserConfigDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, "bender", "bender.db"), nil
}

// Open opens (creating if needed) the database at path and migrates it.
func Open(ctx context.Context, path string) (*Store, error) {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return nil, err
	}
	db, err := sql.Open("sqlite", path+"?_pragma=journal_mode(WAL)&_pragma=busy_timeout(5000)&_pragma=foreign_keys(1)")
	if err != nil {
		return nil, err
	}
	// The UI is the only writer; a second connection would just trade
	// SQLITE_BUSY retries for no benefit.
	db.SetMaxOpenConns(1)
	if err := migrate(ctx, db); err != nil {
		db.Close()
		return nil, err
	}
	return &Store{Queries: New(db), db: db}, nil
}

// Close closes the database.
func (s *Store) Close() error { return s.db.Close() }

// migrate applies embedded migrations newer than PRAGMA user_version.
// Files are named NNNN_name.sql; lexical order is version order.
func migrate(ctx context.Context, db *sql.DB) error {
	var version int
	if err := db.QueryRowContext(ctx, "PRAGMA user_version").Scan(&version); err != nil {
		return err
	}
	files, err := fs.Glob(migrations, "migrations/*.sql")
	if err != nil {
		return err
	}
	for i, file := range files { // fs.Glob returns sorted paths
		v := i + 1
		if v <= version {
			continue
		}
		sqlText, err := migrations.ReadFile(file)
		if err != nil {
			return err
		}
		tx, err := db.BeginTx(ctx, nil)
		if err != nil {
			return err
		}
		if _, err := tx.ExecContext(ctx, string(sqlText)); err != nil {
			tx.Rollback()
			return fmt.Errorf("store: migration %s: %w", file, err)
		}
		// PRAGMA cannot be parameterised; v derives from the loop index.
		if _, err := tx.ExecContext(ctx, fmt.Sprintf("PRAGMA user_version = %d", v)); err != nil {
			tx.Rollback()
			return err
		}
		if err := tx.Commit(); err != nil {
			return err
		}
	}
	return nil
}

// Seed inserts the built-in presets when the services table is empty, so a
// first launch has something to show. No-op otherwise.
func (s *Store) Seed(ctx context.Context) error {
	n, err := s.CountServices(ctx)
	if err != nil {
		return err
	}
	if n > 0 {
		return nil
	}
	for i, p := range service.Presets {
		_, err := s.CreateService(ctx, CreateServiceParams{
			Preset:   p.Key,
			Name:     p.Name,
			Url:      p.URL,
			Profile:  "svc-" + p.Key,
			Position: int64(i),
		})
		if err != nil {
			return err
		}
	}
	return nil
}

// Services returns the enabled services as domain values, in sidebar order.
func (s *Store) Services(ctx context.Context) ([]service.Service, error) {
	rows, err := s.ListEnabledServices(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]service.Service, len(rows))
	for i, r := range rows {
		out[i] = service.Service{
			ID:         r.ID,
			Preset:     r.Preset,
			Name:       r.Name,
			URL:        r.Url,
			Profile:    r.Profile,
			BadgeRegex: r.BadgeRegex,
			Favicon:    r.Favicon,
		}
	}
	return out, nil
}
